# Generated by Django 5.0.7 on 2024-07-25 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_autos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_fabricacion', models.IntegerField()),
                ('cantidad_puertas', models.IntegerField()),
                ('cilindrada', models.FloatField()),
                ('pais_fabricacion', models.CharField(max_length=100)),
                ('precio_dolares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_autos.modeloauto')),
                ('tipo_combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_autos.tipocombustible')),
            ],
        ),
    ]
