# Generated by Django 5.0.7 on 2024-08-08 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_autos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='auto',
            name='pais_fabricacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_autos.pais'),
        ),
    ]
