# Generated by Django 5.0.7 on 2024-08-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_autos', '0007_comentario'),
        ('gestion_autos', '0007_imagenauto'),
    ]

    operations = [
    ]
